### ISSUE TITLE
Liquid Exception: stack level too deep in index.html

### ISSUE THREAD

**Issue by JimSEOW** [chadokruse/chadokruse.github.com#14]
`>jekyll serve
Configuration file: chadokruse/_config.yml
Configuration file: chadokruse/_config.yml
            Source: chadokruse
       Destination: chadokruse/_site
 Incremental build: disabled. Enable with --incremental
      Generating...`

  **Liquid Exception: stack level too deep in index.html**  -- see <<<< where Error happens

ruby/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/url.rb:105:in `find': stack level too deep (SystemStackError)
        from ruby/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/url.rb:105:in `block in generate_url_from_drop'

`<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <div id="allcards">

        
        {% include static-cards/intro-all.html %}
        {% include static-cards/about.html %}

        
       {% assign cards = site.cards | sort: 'sort' %} <<<<
        {% for card in cards %}
          {% include card-template.html %}
        {% endfor %}

        
        {% include static-cards/cc-license.html %}

      </div>

      <div class="landing-cta">
        <p>Looking for a traditional resume? <a href="/resume">Here you go</a></p>
      </div>
    </div>
  </div>
</div>`

**Comment by chadokruse** [comment]
Thanks for the heads up. I suspect my old code isn't compatible with a recent Jekyll update.

I'll try to publish a fix soon, but in the interim try:

```
{% assign cards = site.cards | sort: 'page.sort' %}
```

instead of 

```
{% assign cards = site.cards | sort: 'sort' %}
```
